test: lint charts in the test-apply Makefile target
In case we don't push templates into registry (PUBLIC_REPO == true)
the charts linter is not triggered and charts dependencies are not updated
which leads to the following error:

  Error: An error occurred while checking for chart dependencies.
You may need to run `helm dependency build` to fetch missing dependencies:
found in Chart.yaml, but missing in charts/ directory: flux2, cert-manager,
cluster-api-operator, velero